### ISSUE TITLE
Passing tags is causing errors

### ISSUE THREAD

**Issue by tinfoil-knight** [mrmartineau/gatsby-starter-code-notes#4]
```
GraphQLError: Expected Iterable, but did not find one for field MdxFrontmatter.tags.
```
The log says that it expects an iterable but is unable to find one in MDX Frontmatter. Adding tags while using `gatsby develop` adds the tag to the list of tags but when you click on the list, it leads you to a 404 Page.

**Comment by tinfoil-knight** [comment]
Found the solution: Tags are to be enclosed in `[]` in the frontmatter.

**Comment by mrmartineau** [comment]
H @tinfoil-knight, I’m fairly sure that the tag needs to be there before the build script (`gatsby develop`) is started. 

If I’ve misunderstood the issue, please let me know.

**Comment by tinfoil-knight** [comment]
Hey, tags are be updated even after starting gatsby build. The problem that I had was that passings tags without the brackets was leading to the entire thing breaking down.
Also, one note of appreciation:
Code-notes is genuinely the most useful product I've seen and used this year. Thanks for making it.

**Comment by mrmartineau** [comment]
@tinfoil-knight tags are always an array, even if you have one, so the format is always like this: 

```yaml
tags: 
  - sometag
```

And thanks for the appreciation. I made it for myself so it is awesome to see others using it.
